# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_save_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetSave(object):
    def setupUi(self, WidgetSave):
        WidgetSave.setObjectName("WidgetSave")
        WidgetSave.resize(567, 203)
        self.label_insert_ID_CONTAINER = QtWidgets.QLabel(WidgetSave)
        self.label_insert_ID_CONTAINER.setGeometry(QtCore.QRect(20, 30, 111, 16))
        self.label_insert_ID_CONTAINER.setObjectName("label_insert_ID_CONTAINER")
        self.label_insert_PLATE_CODE = QtWidgets.QLabel(WidgetSave)
        self.label_insert_PLATE_CODE.setGeometry(QtCore.QRect(20, 60, 111, 16))
        self.label_insert_PLATE_CODE.setObjectName("label_insert_PLATE_CODE")
        self.input_driver_name = QtWidgets.QLineEdit(WidgetSave)
        self.input_driver_name.setGeometry(QtCore.QRect(100, 90, 441, 20))
        self.input_driver_name.setObjectName("input_driver_name")
        self.label_insert_DRIVER_NAME = QtWidgets.QLabel(WidgetSave)
        self.label_insert_DRIVER_NAME.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.label_insert_DRIVER_NAME.setObjectName("label_insert_DRIVER_NAME")
        self.input_id_container = QtWidgets.QLineEdit(WidgetSave)
        self.input_id_container.setGeometry(QtCore.QRect(100, 30, 441, 20))
        self.input_id_container.setObjectName("input_id_container")
        self.input_plate_code = QtWidgets.QLineEdit(WidgetSave)
        self.input_plate_code.setGeometry(QtCore.QRect(100, 60, 441, 20))
        self.input_plate_code.setObjectName("input_plate_code")
        self.label_insert_DRIVER_NAME_2 = QtWidgets.QLabel(WidgetSave)
        self.label_insert_DRIVER_NAME_2.setGeometry(QtCore.QRect(20, 120, 111, 16))
        self.label_insert_DRIVER_NAME_2.setObjectName("label_insert_DRIVER_NAME_2")
        self.input_date = QtWidgets.QLineEdit(WidgetSave)
        self.input_date.setGeometry(QtCore.QRect(100, 120, 441, 20))
        self.input_date.setObjectName("input_date")
        self.btn_search = QtWidgets.QPushButton(WidgetSave)
        self.btn_search.setGeometry(QtCore.QRect(260, 160, 75, 23))
        self.btn_search.setObjectName("btn_search")

        self.retranslateUi(WidgetSave)
        QtCore.QMetaObject.connectSlotsByName(WidgetSave)

    def retranslateUi(self, WidgetSave):
        _translate = QtCore.QCoreApplication.translate
        WidgetSave.setWindowTitle(_translate("WidgetSave", "Save"))
        self.label_insert_ID_CONTAINER.setText(_translate("WidgetSave", "ID CONTAINER"))
        self.label_insert_PLATE_CODE.setText(_translate("WidgetSave", "PLATE CODE"))
        self.label_insert_DRIVER_NAME.setText(_translate("WidgetSave", "DRIVER NAME"))
        self.label_insert_DRIVER_NAME_2.setText(_translate("WidgetSave", "DATE"))
        self.btn_search.setText(_translate("WidgetSave", "Search"))
